version: '3.8'

services:
  mysqlhost:
    image: mysql
    container_name: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./init_mysql.sh:/docker-entrypoint-initdb.d/init_mysql.sh

  app:
    build: .
    container_name: app
    environment:
      - START_SERVER=true
    depends_on:
      - mysqlhost
    links:
      - mysqlhost
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/overcooked
      - /overcooked/node_modules/
    command: sh -c "sleep 30 && npm install && npm run dev"